#!/usr/sbin/nft -f

flush ruleset

table inet filter {

    chain input {
        type filter hook input priority 0;
        policy drop;

        # Loopback erlauben
        iif lo accept

        # Bereits bestehende Verbindungen erlauben
        ct state established,related accept

        # ICMP / Ping erlauben (optional aber praktisch)
        ip protocol icmp accept
        ip6 nexthdr icmpv6 accept

        # SSH (optional – Serverzugriff)
        tcp dport 22 accept

        # ===== SAMBA =====

        # SMB
        tcp dport { 139, 445 } accept

        # NetBIOS
        udp dport { 137, 138 } accept

        # ==================
    }

    chain forward {
        type filter hook forward priority 0;
        policy drop;
    }

    chain output {
        type filter hook output priority 0;
        policy accept;
    }
}
